// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyljwzhuvcsmcpstbyqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5bGp3emh1dmNzbWNwc3RieXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjgzNTMsImV4cCI6MjA2ODA0NDM1M30.PdbStP11k-6TXL_SB-DPDxFOiezOGYmZfBaQd624kvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});